### ISSUE TITLE
dscvit.com/morelinks - images look stretched vertically

### ISSUE THREAD

**Issue by BRO3886** [GDGVIT/DSC-official-website#47]
![image](https://user-images.githubusercontent.com/39856034/87656763-8b47de00-c777-11ea-9447-aa0200844c8a.png)

**Comment by BRO3886** [comment]
Also, the link for Idea Hub has a trailing period (.)

and Github shows a 404 

![image](https://user-images.githubusercontent.com/39856034/87657177-16c16f00-c778-11ea-84e3-83fccbb952c7.png)

**Comment by BRO3886** [comment]
@Nirmitjatana

**Comment by BRO3886** [comment]
@Geek-ubaid still not fixed

**Comment by Geek-ubaid** [comment]
Will make sure this is done today only.

**Comment by Nirmitjatana** [comment]
@BRO3886 You can close this issue now!

**Comment by Nirmitjatana** [comment]
> Also, the link for Idea Hub has a trailing period (.)
> 
> and Github shows a 404
> 
> ![image](https://user-images.githubusercontent.com/39856034/87657177-16c16f00-c778-11ea-84e3-83fccbb952c7.png)

@BRO3886 Can you tell more about it, couldn't find this issue

**Comment by Geek-ubaid** [comment]
@Nirmitjatana there is a trailing period in the link that is why the link is showing 404. Remove these unwanted characters!

**Comment by BRO3886** [comment]
> > Also, the link for Idea Hub has a trailing period (.)
> > 
> > and Github shows a 404
> > 
> > ![image](https://user-images.githubusercontent.com/39856034/87657177-16c16f00-c778-11ea-84e3-83fccbb952c7.png)
> 
> @BRO3886 Can you tell more about it, couldn't find this issue

Try clicking on the idea hub image, you'll understand

**Comment by L04DB4L4NC3R** [comment]
> > > Also, the link for Idea Hub has a trailing period (.)
> > > and Github shows a 404
> > > ![image](https://user-images.githubusercontent.com/39856034/87657177-16c16f00-c778-11ea-84e3-83fccbb952c7.png)
> > 
> > 
> > @BRO3886 Can you tell more about it, couldn't find this issue
> 
> Try clicking on the idea hub image, you'll understand

Has been fixed in #48 . Work is being done to avoid streching still.

**Comment by Geek-ubaid** [comment]
Is the issue resolved @Nirmitjatana ?

**Comment by Nirmitjatana** [comment]
> Is the issue resolved @Nirmitjatana ?
> 

Yes.. for now it is resolved
