### ISSUE TITLE
Overlapping of Club LOGO and Home button.

### ISSUE THREAD

**Issue by manishkrjha** [GDGVIT/DSC-official-website#61]
On the <a href="https://dscvit.com/" target="_blank">Home page</a> of club website the logo and the Home button are overlapping in navbar.

![Screenshot (281)_LI](https://user-images.githubusercontent.com/51622948/94811965-b60b0f80-0413-11eb-8443-29b0e66e9bd6.jpg)

**Comment by manishkrjha** [comment]
I'd like to address this issue and add some margin.

**Comment by BRO3886** [comment]
@Nirmitjatana @L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
@manishkrjha sure, open a PR mentioning this issue

**Comment by manishkrjha** [comment]
Can you guys add Hacktoberfest to this issue? 😅

**Comment by akshatvg** [comment]
@manishkrjha added 😃
