### ISSUE TITLE
Add lazy-loading to the feed images

### ISSUE THREAD

**Issue by brij1999** [GDGVIT/DSC-official-website#63]
I would like to work on this issue as a part of #Hacktoberfest. Please let me know if I can go ahead with it, and assign me to this issue.

**Comment by Geek-ubaid** [comment]
> I would like to work on this issue as a part of #Hacktoberfest. Please let me know if I can go ahead with it, and assign me to this issue.

Yes @brij1999 you can definitely contribute to our website repo, feel free to ping if you have any doubt
